name: Unions-OG
main: net.trueog.unionsog.UnionsOG
version: '${version}'
softdepend:
  - DiamondBank-OG
  - PlaceholderAPI
  - Utilities-OG
  - MiniPlaceholders
  - LuckPerms
  - WorldGuard
  - DiscordSRV
loadbefore:
  - GriefPrevention
  - PlotSquared
api-version: '1.13'
authors:
  - Phaed
  - RoinujNosde
website: https://github.com/true-og/Unions-OG
commands:
  clan:
    description: Tells the player to use /union instead
    usage: /union
  clans:
    description: Tells the player to use /union instead
    usage: /union
  factions:
    description: Tells the player to use /union instead
    usage: /union
  guilds:
    description: Tells the player to use /union instead
    usage: /union
  party:
    description: Tells the player to use /union instead
    usage: /union
  tribe:
    description: Tells the player to use /union instead
    usage: /union
  nation:
    description: Tells the player to use /union instead
    usage: /union
  crew:
    description: Tells the player to use /union instead
    usage: /union
  squad:
    description: Tells the player to use /union instead
    usage: /union
  gang:
    description: Tells the player to use /union instead
    usage: /union
permissions:
  unionsog.admin.reload:
    description: Can reload configuration
  unionsog.admin.purge:
    description: Can purge a player
  unionsog.admin.permanent:
    description: Can toggle union permanent status
  unionsog.admin.all-seeing-eye:
    description: Can see all union chats
  unionsog.admin.resetkdr:
    description: Can reset player kdr (of all or just one)
  unionsog.admin.bank.status:
    description: Can check the balance of a union
  unionsog.admin.bank.take:
    description: Can take money from a union
  unionsog.admin.bank.give:
    description: Can give money to a union
  unionsog.admin.bank.set:
    description: Can set the balance of a union
  unionsog.mod.ban:
    description: Can ban players from the entire plugin
  unionsog.mod.disband:
    description: Can disband any union
  unionsog.mod.kick:
    description: Can kick any player
  unionsog.mod.globalff:
    description: Can turn off global friendly fire protection
  unionsog.mod.home:
    description: Can set any union's home
  unionsog.mod.hometp:
    description: Can teleport to all union homes
  unionsog.mod.bypass:
    description: Can bypass restrictions
  unionsog.mod.nopvpinwar:
    description: Can bypass pvp in wars
  unionsog.anyone.list:
    description: Can list unions
  unionsog.anyone.list.balance:
    description: Can list unions by balance
  unionsog.anyone.profile:
    description: Can view a union's profile
  unionsog.anyone.locale:
    description: Can set his language
  unionsog.anyone.roster:
    description: Can veiw a union's member list
  unionsog.anyone.lookup:
    description: Can lookup a player's info
  unionsog.anyone.leaderboard:
    description: Can view the leaderboard
  unionsog.anyone.alliances:
    description: Can view alliances by union
  unionsog.anyone.rivalries:
    description: Can view rivalries by union
  unionsog.anyone.invite-toggle:
    description: Can toggle invite on/off
  unionsog.other.kdr-exempt:
    description: The player's KDR is not affected on killing/dying
    default: false
  unionsog.member.profile:
    description: Can view his own union's profile
  unionsog.member.roster:
    description: Can view his own union's member list
  unionsog.member.lookup:
    description: Can view his own player info
  unionsog.member.vitals:
    description: Can view his union's vitals
  unionsog.member.coords:
    description: Can view his union's coords
  unionsog.member.stats:
    description: Can view his union stats
  unionsog.member.bb:
    description: Can view his union's bulletin board
  unionsog.member.bb-add:
    description: Can add to his union's bulletin board
  unionsog.member.bb-toggle:
    description: Can toggle bb on/off
  unionsog.member.ff:
    description: Can toggle his own friendly fire
  unionsog.member.resign:
    description: Can resign from his union
  unionsog.member.ally:
    description: Can use ally chat
  unionsog.member.chat:
    description: Can use union chat
  unionsog.member.chat.color:
    description: Can use colors in chat
  unionsog.member.chat.format:
    description: Can use formats in chat
    default: false
  unionsog.member.can-join:
    description: Can join unions
  unionsog.member.home:
    description: Can tp to home base
  unionsog.vip.resetkdr:
    description: Can reset his kdr
  unionsog.vip.teleport-delay:
    description: Bypasses the teleport delay
  unionsog.member.create:
    description: Can create unions
  unionsog.member.ally-set:
    description: Can add and remove his union's allies
    default: true
  unionsog.member.rival:
    description: Can start a rivalry with another union
  unionsog.member.modtag:
    description: Can modify his union's tag
    children:
      unionsog.member.color: true
  unionsog.member.color:
    description: Can set his union's color
  unionsog.member.description:
    description: Can modify his union's description
  unionsog.member.bb-clear:
    description: Can clear his union's bb
  unionsog.member.setbanner:
    description: Can set his union's banner
  unionsog.member.rename:
    description: Can rename his union's name
  unionsog.member.disband:
    description: Can propose disbanding his union
  unionsog.member.vote:
    description: Can vote on his union's proposals
  unionsog.member.war:
    description: Can propose a war and answer war requests
  unionsog.member.home-set:
    description: Can propose moving his union's home base
  unionsog.member.regroup.home:
    description: Can tp entire union to homebase
  unionsog.member.regroup.me:
    description: Can tp their entire union to themself
  unionsog.member.discord.create:
    description: Can create discord channel for his union
  unionsog.member.land:
    description: Can use land commands
  unionsog.member.kills:
    description: Can view his and other's kills
  unionsog.member.tag-toggle:
    description: Can hide his own union tag
  unionsog.mod.bb-clear:
    description: Can clear a union's bb
  unionsog.mod.rename:
    description: Can rename a union's name
  unionsog.mod.bb:
    description: Can view a union's bulletin board
  unionsog.mod.bb-add:
    description: Can add to a union's bulletin board
  unionsog.mod.mostkilled:
    description: Can view his and other's unions mostkilled
  unionsog.mod.keep-items:
    description: Can keep items when teleporting home
  unionsog.mod.place:
    description: Can manually place players in unions
  unionsog.mod.modtag:
    description: Can change a union's tag
  unionsog.mod.staffgui:
    description: Can open the staff gui
  unionsog.mod.locale:
    description: Can set players language
  unionsog.member.invite:
    description: Can invite players into his union
  unionsog.member.kick:
    description: Can kick players from his union
  unionsog.member.union-ff:
    description: Can toggle his union's friendly fire
    default: true
  unionsog.member.coloredtag:
    description: Can use color codes in tags
  unionsog.member.bank:
    description: Can use banks
  unionsog.admin.*:
    description: Permissions for admins
    default: op
    children:
      unionsog.admin.reload: true
      unionsog.admin.all-seeing-eye: true
      unionsog.admin.resetkdr: true
      unionsog.admin.permanent: true
      unionsog.admin.bank.status: true
      unionsog.admin.bank.take: true
      unionsog.admin.bank.give: true
      unionsog.admin.bank.set: true
  unionsog.mod.*:
    description: Permissions for moderators
    default: op
    children:
      unionsog.mod.ban: true
      unionsog.mod.disband: true
      unionsog.mod.kick: true
      unionsog.mod.globalff: true
      unionsog.mod.bypass: true
      unionsog.mod.home: true
      unionsog.mod.mostkilled: true
      unionsog.mod.keep-items: true
      unionsog.mod.nopvpinwar: true
      unionsog.mod.place: true
      unionsog.mod.staffgui: true
      unionsog.mod.modtag: true
      unionsog.mod.bb-clear: true
      unionsog.mod.bb: true
      unionsog.mod.bb-add: true
      unionsog.mod.locale: true
  unionsog.anyone.*:
    description: Permissions for anyone
    default: true
    children:
      unionsog.anyone.list: true
      unionsog.anyone.profile: true
      unionsog.anyone.roster: true
      unionsog.anyone.lookup: true
      unionsog.anyone.leaderboard: true
      unionsog.anyone.alliances: true
      unionsog.anyone.rivalries: true
      unionsog.anyone.invite-toggle: true
      unionsog.anyone.locale: true
  unionsog.member.land.*:
    description: Permissions for allowing/blocking actions in lands
    default: false
    children:
      unionsog.member.land.allow.container: true
      unionsog.member.land.allow.place: true
      unionsog.member.land.allow.damage: true
      unionsog.member.land.allow.break: true
      unionsog.member.land.allow.interact: true
      unionsog.member.land.allow.interact_entity: true
      unionsog.member.land.block.container: true
      unionsog.member.land.block.place: true
      unionsog.member.land.block.damage: true
      unionsog.member.land.block.break: true
      unionsog.member.land.block.interact: true
      unionsog.member.land.block.interact_entity: true
  unionsog.member.*:
    description: Permissions for those who can be union members
    default: true
    children:
      unionsog.member.land: true
      unionsog.member.land.*: true
      unionsog.member.can-join: true
      unionsog.member.profile: true
      unionsog.member.roster: true
      unionsog.member.lookup: true
      unionsog.member.vitals: true
      unionsog.member.coords: true
      unionsog.member.stats: true
      unionsog.member.bb: true
      unionsog.member.bb-add: true
      unionsog.member.bb-toggle: true
      unionsog.member.cape-toggle: true
      unionsog.member.tag-toggle: true
      unionsog.member.ff: true
      unionsog.member.resign: true
      unionsog.member.ally: true
      unionsog.member.chat: true
      unionsog.member.home: true
      unionsog.member.kills: true
      unionsog.member.bank: true
      unionsog.member.chat.color: true
      unionsog.member.rename: true
      unionsog.member.disband: true
      unionsog.member.vote: true
      unionsog.member.war: true
      unionsog.member.home-set: true
      unionsog.member.regroup.home: true
      unionsog.member.regroup.me: true
      unionsog.member.discord.create: true
      unionsog.member.create: true
      unionsog.member.ally-set: true
      unionsog.member.rival: true
      unionsog.member.modtag: true
      unionsog.member.color: true
      unionsog.member.cape: true
      unionsog.member.invite: true
      unionsog.member.kick: true
      unionsog.member.union-ff: true
      unionsog.member.withdraw-toggle: true
      unionsog.member.deposit-toggle: true
      unionsog.member.coloredtag: true
      unionsog.member.bb-clear: true
      unionsog.member.setbanner: true
      unionsog.member.description: true
